# Generated by Django 2.2.16 on 2020-11-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rover',
            fields=[
                ('rover_id', models.CharField(max_length=60, primary_key=True, serialize=False, unique=True)),
                ('session_id', models.CharField(max_length=60)),
                ('session_start', models.FloatField()),
                ('last_timestamp', models.FloatField()),
            ],
        ),
    ]
